apiVersion: v1
kind: Service
metadata:
  name: predictor
  labels:
    app.kubernetes.io/name: predictor
spec:
  selector:
    app.kubernetes.io/name: predictor
  ports:
    - name: http
      port: 8080
      targetPort: http
