apiVersion: v1
kind: Service
metadata:
  name: diagnosis-agent
  labels:
    app.kubernetes.io/name: diagnosis-agent
spec:
  selector:
    app.kubernetes.io/name: diagnosis-agent
  ports:
    - name: http
      port: 8080
      targetPort: http
