apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - rbac.yaml
  - network-policies.yaml
  - apps/hello
  - apps/demo-api
  - apps/predictor
  - apps/prometheus
  - apps/loki
  - apps/promtail
  - apps/grafana
