apiVersion: v1
kind: Namespace
metadata:
  name: sentinel
  labels:
    app.kubernetes.io/part-of: sentinel
---
apiVersion: v1
kind: Namespace
metadata:
  name: sentinel-system
  labels:
    app.kubernetes.io/part-of: sentinel
