apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-workload
  namespace: sentinel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sentinel-workload
  namespace: sentinel
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sentinel-workload
  namespace: sentinel
subjects:
  - kind: ServiceAccount
    name: sentinel-workload
    namespace: sentinel
roleRef:
  kind: Role
  name: sentinel-workload
  apiGroup: rbac.authorization.k8s.io
