apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data
  labels:
    app.kubernetes.io/name: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
